# Generated by Django 5.2.7 on 2025-10-17 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=40)),
                ('etiqueta', models.CharField(blank=True, max_length=120)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=8)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='cartera_eve_ts_c0e647_idx'), models.Index(fields=['nombre', 'categoria'], name='cartera_eve_nombre_43dfb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NAT', 'Natura'), ('ACC', 'Accesorios'), ('OTR', 'Otros')], max_length=3)),
                ('campania', models.CharField(blank=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('hora_pago', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='cartera.cliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
