# Generated by Django 5.2.7 on 2025-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
