# Generated by Django 5.2.7 on 2025-10-17 18:48

import cartera.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_transaccion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo', models.CharField(choices=[('EFE', 'Efectivo'), ('TRF', 'Transferencia'), ('OTR', 'Otro')], default='TRF', max_length=3)),
                ('fecha', models.DateField(default=cartera.models.current_local_date)),
                ('hora', models.TimeField(default=cartera.models.current_local_time)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.transaccion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
