# Generated by Django 5.2.7
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from django.core.validators import MinValueValidator

def forward_migrar_descripcion_a_items(apps, schema_editor):
    Transaccion = apps.get_model("cartera", "Transaccion")
    TransaccionItem = apps.get_model("cartera", "TransaccionItem")
    # Si el modelo anterior tenía 'descripcion', la tomamos
    for tx in Transaccion.objects.all():
        # getattr por si el estado previo aún lo tiene en DB
        desc = getattr(tx, "descripcion", None)
        if desc:
            TransaccionItem.objects.create(
                transaccion=tx,
                producto=str(desc)[:200],
                precio_unitario=0,
                cantidad=1,
                descuento=0,
            )

def backward_borrar_items_migrados(apps, schema_editor):
    TransaccionItem = apps.get_model("cartera", "TransaccionItem")
    # Limpiamos ítems que creamos en forward
    TransaccionItem.objects.filter(precio_unitario=0, cantidad=1, descuento=0).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("cartera", "0003_abono"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransaccionItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, auto_created=True, serialize=False, verbose_name="ID")),
                ("producto", models.CharField(max_length=200)),
                ("precio_unitario", models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)], default=0)),
                ("cantidad", models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)], default=1)),
                ("descuento", models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(0)], default=0)),
                ("transaccion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="cartera.transaccion")),
            ],
            options={"verbose_name": "Ítem de transacción", "verbose_name_plural": "Ítems de transacción"},
        ),
        migrations.AddField(
            model_name="transaccion",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="pagado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Mover descripcion -> un item
        migrations.RunPython(forward_migrar_descripcion_a_items, backward_borrar_items_migrados),
        # Quitar descripcion
        migrations.RemoveField(
            model_name="transaccion",
            name="descripcion",
        ),
    ]
