# Generated by Django 5.2.7 on 2025-10-19 19:24

import cartera.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_items_y_sin_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoAnalitica',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='hora_pago',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='valor',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=cartera.models.current_local_date),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=cartera.models.current_local_time),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='campania',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='cartera.cliente'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('NAT', 'Natura'), ('ACC', 'Accesorios'), ('OTR', 'Otros')], default='OTR', max_length=3),
        ),
    ]
