# Generated by Django 5.2.7 on 2025-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_delete_eventoanalitica_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionitem',
            name='descuento',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], null=True),
        ),
    ]
