# Generated by ChatGPT on 2026-02-14

from django.db import migrations, models
from django.db.models import Q


def map_abono_metodos(apps, schema_editor):
    Abono = apps.get_model("cartera", "Abono")
    # TRF -> BAN (Bancolombia), OTR -> EFE (Efectivo)
    Abono.objects.filter(metodo="TRF").update(metodo="BAN")
    Abono.objects.filter(metodo="OTR").update(metodo="EFE")


class Migration(migrations.Migration):

    dependencies = [
        ("cartera", "0006_alter_transaccionitem_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="fecha_pago",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaccionitem",
            name="codigo_producto",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="abono",
            name="descripcion_cruce",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="abono",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("NEQ", "Nequi"),
                    ("BAN", "Bancolombia"),
                    ("EFE", "Efectivo"),
                    ("CRU", "Cruce de cuentas"),
                ],
                default="BAN",
                max_length=3,
            ),
        ),
        migrations.RunPython(map_abono_metodos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                fields=("telefono",),
                condition=~Q(telefono=""),
                name="uniq_cliente_telefono_no_vacio",
            ),
        ),
    ]
